# Generated by Django 3.1.3 on 2020-12-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('نور', models.CharField(blank=True, max_length=100)),
                ('خاک', models.CharField(blank=True, max_length=100)),
                ('دما', models.CharField(blank=True, max_length=100)),
                ('آبیاری', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
