# Generated by Django 3.1.3 on 2020-12-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_karbar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karbar',
            old_name='name',
            new_name='شماره_تلفن_همراه',
        ),
        migrations.RenameField(
            model_name='karbar',
            old_name='name_flower',
            new_name='نام',
        ),
        migrations.RenameField(
            model_name='karbar',
            old_name='number',
            new_name='نام_گیاه',
        ),
    ]
