# Generated by Django 3.1.3 on 2020-12-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20201230_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karbar',
            old_name='شماره_تلفن_همراه',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='karbar',
            old_name='نام',
            new_name='name_flower',
        ),
        migrations.RenameField(
            model_name='karbar',
            old_name='نام_گیاه',
            new_name='number',
        ),
    ]
