# Generated by Django 3.1.4 on 2020-12-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20201230_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='karbar',
        ),
    ]
